### ISSUE TITLE
Broken on touch devices

### ISSUE THREAD

**Issue by jimmynotjim** [jimmynotjim/scrollNav#4]
Jumps around when switching from absolute to fixed positioning and the active section doesn't always update.

**Comment by abipro** [comment]
hi what is the status of this bug am facing problem with scroll nav kindly tell or suggest other plugin for header effect

**Comment by jimmynotjim** [comment]
It's a matter of touch devices not updating until you lift up your finger. For iOS devices you can now use `position: sticky` but it's yet to land on other platforms. Check [Can I Use](http://caniuse.com/#feat=css-sticky) for the latest support.

**Comment by jimmynotjim** [comment]
Closing because `position: sticky` has reached good coverage and there are plenty of options to [fix older browsers](https://css-tricks.com/stickybits-alternative-position-sticky-polyfills/)
