### ISSUE TITLE
Stop menu when reaching the footer

### ISSUE THREAD

**Issue by conradr** [jimmynotjim/scrollNav#42]
I'm not sure if this is intended but when you have a large footer the nav scrolls past the body and overlaps the footer.

Is there a way to stop the nav from scrolling or hide it when reaching a certain part of the viewport?
See this for a demo:
http://codepen.io/anon/pen/yICcF

**Comment by saltcod** [comment]
Just discovered this issue today. Anyone come across any ideas in the last 2 years ish before I dive in? 

Thanks! 

I'll report back if I find anything of use.

**Comment by saltcod** [comment]
Ps: My immediate thought on this would be to detect when the nav reaches the bottom of the adjacent container and trigger a class change that changes from position fixed to position absolute, bottom: 0; 

This way, the nav would stick to the bottom of that container until you scrolled back up.
