### ISSUE TITLE
Using _check_pos and offset for assigning active class to nav a href

### ISSUE THREAD

**Issue by sumlah** [jimmynotjim/scrollNav#56]
Quite possible that I've made too many modifications to my own stuff regarding the offset, but I was running into an issue where the last <a> link in the navigation menu wouldn't take the class of "active."

The _check_pos function has the following code at line 213-217:
$.each(S.sections.data, function(index) {
   if ((this.top_offset > boundry_top && this.top_offset < boundry_bottom) || 
        (this.bottom_offset > boundry_top && this.bottom_offset < boundry_bottom) || 
        (this.top_offset < boundry_top && this.bottom_offset > boundry_bottom) || 
        (this.top_offset === boundry_top && this.bottom_offset === boundry_bottom)) {
             sections_active.push(this);
     }
});

However, if I set my scrollOffset to 0, it fails to match any of those above _check_pos conditions.

$('.maincontent').scrollNav({    
    scrollOffset: 0,
    animated: true, // animate the scroll
    speed: 500, // animate scroll at 500 speed
    insertTarget: this.selector,
    insertLocation: 'insertBefore', // inserts the scroll-nav
    arrowKeys: true, // allow use of arrow keys for scrolling through navigation
    onInit: null,
    onRender: null,
    onDestroy: null
});

I added this line of code to the conditions and it resolved my issue:
|| (this.top_offset === boundry_top && this.bottom_offset === boundry_bottom)

Final chunk of code looks like this:
$.each(S.sections.data, function(index) {
     if ((this.top_offset > boundry_top && this.top_offset < boundry_bottom) || 
        (this.bottom_offset > boundry_top && this.bottom_offset < boundry_bottom) || 
        (this.top_offset < boundry_top && this.bottom_offset > boundry_bottom) || 
        (this.top_offset === boundry_top && this.bottom_offset === boundry_bottom)) {
             sections_active.push(this);
     }
});

**Comment by jimmynotjim** [comment]
Ah ok, well if you do find that your changes are worth including, feel free to reopen this issue or open a pull request.
