### ISSUE TITLE
Multilevel nav style

### ISSUE THREAD

**Issue by ibc** [jimmynotjim/scrollNav#60]
I want all these levels to be shown in the menu:

```
sections: 'h2, h3, h4'
```

But all those entries have the same attributes within the nav menu so I cannot apply different styles for h2, h3, etc. Do I miss something?

```
<nav class="scroll-nav" role="navigation">
  <div class="scroll-nav__wrapper">
    <ol class="scroll-nav__list">
      <li class="scroll-nav__item">
        <a href="#scrollNav-1" class="scroll-nav__link">Foo class</a>
      </li>
      <li class="scroll-nav__item">
        <a href="#scrollNav-2" class="scroll-nav__link">Properties</a>
      </li>
```

How could I apply different CSS style to h1 entries ("Foo class") and h2 ones ("Properties")?

**Comment by ibc** [comment]
I'm playing with `subSections` and `sectionElem` but I don't get it properly working. Basically I have this structure:

```html
<h2>Class</h2>

<h3>Properties</h3>

<section>
  <h4>version</h4>
  <h4>name</h4>
</section>
```

I need that the resulting menu has 3 levels of nested lists so I can apply CSS according to the exact level (h2, h3 or h4).

I think I've tried every combination of settings without success... Do I miss something?

Thanks a lot.

**Comment by ibc** [comment]
Mmm, I should assume that just two levels are allowed, am I right?

**Comment by jimmynotjim** [comment]
Yes, only two are allowed. The biggest issue is the more items you add the more unruly scrollNav becomes and on small screens you lose the content. One solution is to set the Y axis to scroll the overflow but it's not optimal.

The other issue is scrollNav is tracking each section and sub-section as you scroll the page. If you were to break them further and further into sub-sections performance would take a horrible hit.

I'm sorry it doesn't do exactly what you're looking for, but hopefully you can work with the two levels of headings.

**Comment by ibc** [comment]
Thanks a lot for the explanation :)
