### ISSUE TITLE
Possibility to add sub sections that are 1 to 2 level deep.

### ISSUE THREAD

**Issue by Okami-** [jimmynotjim/scrollNav#65]
Trying to add h3's as subsections that are nested 2 levels deep below the h2 sections. Wondering if there is code you could share if not possible for a future implementation.

**Comment by jimmynotjim** [comment]
Sorry about the delay getting back to you. It doesn't matter how deep they are nested, adding `subSections: 'h3'` to the options object should find them. If it's not working for you, please post a demo somewhere like codepen or jsfiddle and I'll be sure to take a look.
