### ISSUE TITLE
Multiple TOC Items Highlighting at Once

### ISSUE THREAD

**Issue by JoshuaLewis** [jimmynotjim/scrollNav#71]
To see this issue live scroll down the following page, the TOC is on the left: http://peakface.com/toc/

You will notice that at times multiple TOC items are highlighted at the same time. As I understand it this is due to you being over multiple sections at the same time:

![section-highlight](https://cloud.githubusercontent.com/assets/4361528/14229388/70ef0f96-f8e7-11e5-9d3a-b089605cc0f0.png)

It should only highlight the section you just passed, highlighting multiple items at the same time is confusing to the viewer as to where you are. Theoretically in the screen shot example it should only highlight the camping item instead of three at once.

Edit: It seems to be related to the active class not shifting over from the top item.

**Comment by jimmynotjim** [comment]
Glad you got it figured out.
