### ISSUE TITLE
Better Hash/Anchor Names for the TOC

### ISSUE THREAD

**Issue by JoshuaLewis** [jimmynotjim/scrollNav#72]
I want to first congratulate/thank you guys on this great plugin.

It would be great if the anchors had better names than just "#scrollNav-4" or whatever the anchor number is. So for example if I had a header called "Getting There",
it would be awesome to get a URL of "#getting-there". It's SEO friendly, makes for better link sharing, and reduces the chances of broken hash links. I often find myself swapping content sections for better page organization. So if I swapped the content of #scrollNav-4, it would no longer link to the right place (assuming someone linked to this from another website). Better hash names remove this issue because it will consistently link to the same place regardless of placement. :-)

**Comment by jimmynotjim** [comment]
What if the heading already has an id of `getting-there`, which it probably should if you want to link to it in case the JS fails or you stop using the plugin? That would result in duplicate IDs. What if instead, we check for an id on the heading, and if it exists, remove it from the heading and set it on the section in place of the generic `scrollNav-` id. 

I don't know that I'll have time for this in the next month, we're releasing a product and I'll be traveling two of the next four weeks, but if you feel inclined, I'd be happy to set aside time to test a PR. Let me know.

**Comment by JoshuaLewis** [comment]
Manually inserting id's isn't as ideal for headers in case of changing the name. Plus it's more work if you are often inserting headers into dozens of articles often.

As for the replacement idea, sounds like a good work around. Another idea would be to have ScrollNav use the name attribute in headers. If the method you mentioned is too much work and if you are worried about some users running into conflict, we could have the "clean hash" as an option.

As for timing, no worries, I'm mainly focused on getting things better for the future. ;-) Unfortunately I'm not very good at Jquery, I just happen to know how to tweak it and do some very basic stuff along with testing and figuring out logical issues. Eventually I plan on learning a lot more about the JS world.

**Comment by JoshuaLewis** [comment]
I looked into this more and was able to tweak other code out there and then add in a few more methods to produce this: 

`$('.article-text h2').each(function() {
    		$(this).attr("id", $(this).text().replace(/ /g, '-').toLowerCase().trim());
		});`

This function automatically creates beautiful id's for each header while stripping away extra space.

**Comment by jimmynotjim** [comment]
It's not about how easy or hard it is, that's trivial. It's about what features should be supported (I'd argue the plugin is getting bloated) and not creating clashes with ID's user's are already using. I'm also concerned about stringify-ing a heading like "Check out this really cool content, it's amazing", or even longer. Sorry about the delay in responding, we relaunched our site last week and I was heads down. I'll think this over and update soon.

**Comment by JoshuaLewis** [comment]
The same logic could be applied to name anchors instead so that there is no ID conflicts.

**Comment by jimmynotjim** [comment]
I've added this to the list of priorities for the next version, see #86 for more details.

**Comment by jimmynotjim** [comment]
@JoshuaLewis after thinking on it, I decided I'd rather users set their custom IDs in the markup than add a new option to the plugin. It's far simpler than maintaining a stringifyer or other solution (plus the related tests) and ensures the IDs are persistent, even if the plugin fails or you stop using it. If you're dead set on a stringified heading, there are options for nearly every backend language and some platforms even build it in (like Jekyll). An early version is working in the [codepen experiment](https://codepen.io/jimmynotjim/pen/vRyJPJ?editors=0010) where you can see some headings have IDs and some don't. I've already added the utility (plus tests) to [the v3 branch](https://github.com/jimmynotjim/scrollNav/blob/prerelease-v3.0.0/src/utils/getOrSetID.js) 

I'm going to consider this issue resolved, but feel free to continue the discussion if you see potential issues with this solution.
