### ISSUE TITLE
Large articles do not properly render TOC highlight upon first load

### ISSUE THREAD

**Issue by JoshuaLewis** [jimmynotjim/scrollNav#74]
The navigator highlighter will be active long before actually getting to the headers it's supposed to highlight.

Refresh the page, you will notice that it suddenly works 100% as expected (as in highlighting "waits" until you actually scroll to the next header). I'm guessing this has something to do with the images themselves being cached, hence affecting how the anchors are loaded.

**Comment by jimmynotjim** [comment]
I think you need to defer loading until you're sure the images are loaded. My guess is the plugin is calculating page positions before the images are loaded, but not recognizing the change and recalculating after. If you defer it you shouldn't have this issue.

**Comment by JoshuaLewis** [comment]
Perhaps due to my limited knowledge of Jquery I was not able to get `$(document).ready() ` to work on my script. Now I know I load a lot of images in, but even if someone had a few iframes or a small gallery this would still mess with positioning for others. So perhaps this deferred method should be the default? Unless of course you are worried about people not seeing their TOC in a timely manner. However if that was the case, odds are that it was because of "too much media" which would generate the issue I'm having.

**Comment by jimmynotjim** [comment]
No, that's not how plugins should work. The plugin should only do what it's designed to do, and you as a developer are responsible for the architecture to support that. The other option you have is to use the available methods to update everything on dom changes -> https://github.com/jimmynotjim/scrollNav#reset-positions-on-dom-change

**Comment by JoshuaLewis** [comment]
Loading content from <img src="source.jpg"> is considered a DOM change? (img tag is loaded before any scripts) I thought the tag itself is the element and the source is simply the content being loaded into it, hence no DOM change.

**Comment by jimmynotjim** [comment]
No, but if you do something like

```
$( document ).ready(function() {
    $.fn.scrollNav('resetPos');
});
```

It should keep the nav from being delayed while giving you the correct locations after the images have completed.
