### ISSUE TITLE
Feature request: add active class to section

### ISSUE THREAD

**Issue by ljodx** [jimmynotjim/scrollNav#75]
Hello, thank you for the plugin!

Is it possible to add a feature which would append an active class to the section currently in view?

**Comment by jimmynotjim** [comment]
It certainly could be but I unfortunately haven't had time to actively develop this project since it's no longer part of my daily work. PRs area always welcome if you want to take it on yourself.

**Comment by jimmynotjim** [comment]
The next version of scrollNav will not be modifying the content with section wrappers. Sadly this feature will no longer be possible at all without those wrappers.
