### ISSUE TITLE
Add `onScrolled` callback

### ISSUE THREAD

**Issue by wujekbogdan** [jimmynotjim/scrollNav#77]
scrollNav is great but there's on major feature missing - the URL is not updated after scroll. I wanted to implement it manually, but there's no callback fired after scroll, so I'm unable to update the URL manually.

**Comment by jimmynotjim** [comment]
This is also a great idea. If you wanted to add it I'd be very appreciative. If not, I'll add it to my list for when I get the time.

**Comment by jimmynotjim** [comment]
@wujekbogdan I've added this to the list of features planned for v3. Closing this issue in favor of https://github.com/jimmynotjim/scrollNav/issues/86#issuecomment-381827547
