### ISSUE TITLE
f.nextUntil(...).andSelf is not a function (jQuery v3 incompatibility)

### ISSUE THREAD

**Issue by DDiran** [jimmynotjim/scrollNav#79]
Hey there,

I followed the guidelines/instructions to the letter, and when I load the page I get the following console error:

`f.nextUntil(...).andSelf is not a function
 at Object._find_sections (jquery.scrollNav.min.js:4)
    at HTMLElement.<anonymous> (jquery.scrollNav.min.js:4)
    at Function.each (jquery-3.1.1.min.js:2)
    at r.fn.init.each (jquery-3.1.1.min.js:2)
    at r.fn.init.init (jquery.scrollNav.min.js:4)
    at r.fn.init.a.fn.scrollNav (jquery.scrollNav.min.js:4)
    at custom.js:80`

Any ideas what the issue could be?

**Comment by jimmynotjim** [comment]
@DDiran that's odd, I haven't seen that before. Do you have a sample I can check? I wonder if jQuery v3 removed something, I haven't tested it with the plugin.

**Comment by DDiran** [comment]
Sure thing, I have uploaded the relevant section to http://scrollnav.bss.design/

**Comment by DDiran** [comment]
Thanks for the quick reply - you can find the sample here -> http://scrollnav.bss.design/

**Comment by DDiran** [comment]
Hmmm actually I just noticed the issue isn't the same on the sample?? So weird! This is what I'm getting https://gyazo.com/8a63adc7cdb1bc45b39d993d15f7bbab

**Comment by DDiran** [comment]
OK so I changed my jQuery version from 3.x to 2.x and it seems to be working now - so the issue is most likely compatibility with the latest jQuery.

**Comment by jimmynotjim** [comment]
@DDiran thanks for following up. I'm not sure when or if this project will support jQuery v3 or higher. I don't use it for my day-to-day any more, so I seldom have time to work on it, unfortunately. If I find the time, I'll be sure to reply here.

**Comment by sheeep** [comment]
For anyone wondering, the function `andSelf` was removed in jQuery3. Replace any occurrences of `andSelf` with `addBack` and your good to go again.

https://github.com/jimmynotjim/scrollNav/pull/85

**Comment by jimmynotjim** [comment]
This was merged a while back and released yesterday. Sorry for the delay, this project had unfortunately fallen quite a bit in priorities for the last few years. Trying to improve that going forward.
