### ISSUE TITLE
Error when running `grunt default` (for development)

### ISSUE THREAD

**Issue by pixelbandito** [jimmynotjim/scrollNav#80]
When I run `grunt jshint` or any task that includes it, I see this error:
```sh
Warning: Path must be a string. Received null Use --force to continue.
``` 

After a little digging, I think it's due to a missing "reporterOutput" property, possibly from more recent versions of JSHint.

I have JSHint version 2.5.11 in my node_modules folder.

**Comment by jimmynotjim** [comment]
Fixed with #81
