### ISSUE TITLE
v3 Request for feedback

### ISSUE THREAD

**Issue by jimmynotjim** [jimmynotjim/scrollNav#86]
After a long hiatus I'm finally setting aside time to work on this project again. I've come up with a list of priorities for the next release and would like feedback from anyone that's used scrollNav in production, and especially from those that have contributed to the project in the past. If you have features or changes you'd like to see, or if you'd like to lend a hand with ones I've identified, please leave a comment.

- [x] Re-written in native ES6 - It's finally time, if you're already transpiling your project's code there's no reason for plugins to include excess baggage you don't need.
  - For those that can't/aren't transpiling, deploy an ES5/jQuery version in addition to the ES6 version
- [x] Create debug method for debugging - Right now it's automatically included in production code which is unnecessary
  - Move logging to debug mode
  - Add visual cues when enabled (highlight active section of screen)
- [x] Stop modifying the page content other than inserting IDs and links - 
  - Stop adding section elems. Addresses #78. I've been thinking about this a lot the last few months and I'm think I may have a solution
  - Ensure existing IDs aren't overwritten
  - Touch the DOM as little as possible
- [x] Reduce customizations - It's gotten out of hand, and as nice as it is for users to change classnames or make tweaks, the code has become a bit unruly as a result. Not sure what to trim just yet, but looking for feedback on what's absolutely necessary vs nice-to-have. NOTE: See comment below for list of option priorities.
- [x] Documentation and playground - The docsite could use a refresh
  - need a plan for allowing users of v2 to continue referencing docs
  - would love to have a playground where it's easy to experiment with the code
- [x] Address small screen usage - Let's face it, it sucks. 
  - Possible solution is to use a toggle to show/hide the ToC, like a hamburger menu
  - Not sure how that fits within this codebase, seems impossible to enforce the same solution on every project, but the docs and playground could address it

cc. @MeghdadHadidi @RobLoach @willthemoor @marcamos @germanny @sheeep @pixelbandito @Borzik @thomasguillory 

_Note: I apologize in advance if you are no longer using scrollNav and I included you in the mentions above. I want to ensure that anyone that has contributed and may still be interested is given a chance to be heard or help. If you're not interested I won't be offended if you mute this thread and ask to be removed from any future mentions._

**Comment by RobLoach** [comment]
Sounds exciting that you're looking to revamp what and how scrollNav does. I'll be able to take a look later this week.

**Comment by jimmynotjim** [comment]
A really rough and messy demo (subject to break as I play tweak things) is up on CodePen https://codepen.io/jimmynotjim/pen/vRyJPJ?editors=0010

So far I've stripped jQuery and any outside deps, improved the highlighting logic while removing unnecessary DOM insertions, added a visual debugger (mostly for my sanity), and reduced the customizations (as in almost none at the moment). Nav building, active highlighting, and scroll on click are all working really well. 

I think at this point I'm going to update the build toolchain and start working on some unit tests. If you're interested in lending a hand or just following along, [checkout the working branch](https://github.com/jimmynotjim/scrollNav/tree/prerelase-v3.0.0) (nothing new there just yet).

**Comment by jimmynotjim** [comment]
v3 is [coming along nicely](https://github.com/jimmynotjim/scrollNav/commits/prerelease-v3.0.0). So far I've rewritten everything in native ES6, with a bit of ES7 (just async/await). I'm still not sure exactly how I'll bundle the distributed versions, but plan to publish both raw and transpiled files. I was able to update the active section logic to avoid wrapping sections and in my mind improve the experience a bit. It's now far less likely the last section is impossible to highlight. Lastly I removed all of the options entirely, and am trying to decide what's necessary vs what's nice to have. Here's my list so far

Necessary:
- `sections` - section elements to search for
- `subSections` - sub-section elements to search for, default is to not include sub-sections
- `insertTarget` - The page element to target when inserting the nav
- `insertLocation` - The location relative to the `insertTarget` to insert the nav
- `onInit` - callback for after the nav is initialized
- `onDestroy` - callback for after the nav is removed

Nice to have:
- `onClick` - callback for after the user clicks a nav item
- `onActive` - callback for when a section becomes active

Possibly no longer necessary:
- `sectionElem` - no longer wrapping sections so this doesn't need to exist
- `showHeadline` and `headlineText` - I rarely find this used, if you use it and need it, chime in
- `showTopLink` and `topLinkText` - same, if no one is using this lets kill it
- `fixedMargin` - now that `position: sticky` is available there's no reason to force the positioning in JS
- `scrollOffset` - it's more opinionated, but the user experience is improved when the active area is predetermined 
- `animated` - I've never seen this set to static before
- `speed` - the speed is now calculated as part of the distance to scroll and I don't see a reason to adjust it
- `arrowKeys` - this was a bad idea, users of screen readers rely on the arrow keys to navigate a page's content. Taking control of them is hostile to these users.

Additionally I'm thinking the methods to include are:

- `init` - obvious, but initializes the nav
- `destroy` - removes the nav and all the event listeners the script created
- `resetPositions` - updates the data array with all the new locations of the sections
- `scrollTo` - since we've gone through the trouble of creating the code we might as well expose this for situations someone would want to write a script to scroll the window outside of the nav controls. I'm thinking this can replace the top link options by a user adding a link to the nav via the `onInit` option.

**Comment by jimmynotjim** [comment]
PR #92 is open and available for review/testing, still need to work through deployment process (polyfills and jQuery support for those that want it) and docs/playground, but the core of the work is complete.

**Comment by jimmynotjim** [comment]
Now that the plugin is nearly complete, I've started working on improving the documentation, including a whole new website. Other than a playground and different examples of how scrollNav can be used, what is currently missing from the docs/website?

**Comment by jimmynotjim** [comment]
Finally! https://github.com/jimmynotjim/scrollNav/pull/98 Unless I find an issue with the final round of testing, this'll be merged and released before Christmas.

**Comment by jimmynotjim** [comment]
And it's live. 🤞
